# Generated by Django 4.0.3 on 2022-12-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_alter_shoes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binvo',
            options={'verbose_name': 'BinVO', 'verbose_name_plural': 'BinVO'},
        ),
    ]
