# Generated by Django 4.0.3 on 2022-12-03 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0004_alter_binvo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binvo',
            options={},
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='bin_size',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='closet_name',
        ),
    ]
